apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/configmap.yaml
  - postgres/pvc.yaml
  - postgres/service.yaml
  - postgres/deployment.yaml

  - backend/service.yaml
  - backend/deployment.yaml
  - backend/configmap.yaml
  - backend/migration-job.yaml

  - frontend/service.yaml
  - frontend/deployment.yaml

images:
  - name: pragg3/pulsewatch-backend
    newTag: e5f0d376dd716da5872aaf9b6ac013f383b797d5

  - name: pragg3/pulsewatch-frontend
    newTag: e5f0d376dd716da5872aaf9b6ac013f383b797d5
    
