apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/configmap.yaml
  - postgres/pvc.yaml
  - postgres/service.yaml
  - postgres/deployment.yaml

  - backend/service.yaml
  - backend/deployment.yaml
  - backend/migration-job.yaml

  - frontend/service.yaml
  - frontend/deployment.yaml

images:
  - name: pragg3/pulsewatch-backend
    newTag: b335c168a371f8c23af478fb973f3b755e7f3b38

  - name: pragg3/pulsewatch-frontend
    newTag: b335c168a371f8c23af478fb973f3b755e7f3b38
    
