apiVersion: apps/v1
kind: Deployment

metadata:
  name: pulsewatch-postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: pulsewatch-postgres

  template:
    metadata:
      labels:
        app: pulsewatch-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:17

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data


          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - pulsewatch
                - -d
                - pulsewatch
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - pulsewatch
                - -d
                - pulsewatch
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-data